name: Cypress tests
on: [push, pull_request]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04

    services:
      # postgres:
      #   image: postgres:11
      #   env:
      #     POSTGRES_USER: lemongrass
      #     POSTGRES_DB: partnership_test
      #     POSTGRES_PASSWORD: "POIpoi123"
      #   ports: ["5432:5432"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: 2.6.5

      # - name: Ruby gem cache
      #   uses: actions/cache@v1
      #   with:
      #     path: vendor/bundle
      #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-gems-

      # - name: Install gems
      #   run: |
      #     bundle config path vendor/bundle
      #     bundle install --jobs 4 --retry 3

.      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.13.0

      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      # - name: Setup test database
      #   env:
      #     RAILS_ENV: test
      #     DB_HOST: localhost
      #   run: |
      #     bin/rails db:setup

      # - name: Run delayed_job
      #   env:
      #     RAILS_ENV: test
      #     DB_HOST: localhost
      #   run: |
      #     bin/delayed_job start


      - name: Cypress run
        uses: cypress-io/github-action@v2.3.8
        with:
          # env: host=localhost,port=3000
          # start: bundle exec rails s -p 3000 -b 0.0.0.0
          # wait-on: 'http://localhost:3000'
          # record: true
          project: ./cypress
          browser: chrome
        env:
          # RAILS_ENV: test
          # pass the Dashboard record key as an environment variable
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          
      # - name: 'Upload Cypress videos and screenshots when fail'
      #   uses: actions/upload-artifact@v2
      #   if: failure()
      #   with:
      #     name: cypress_videos
      #     path: /home/runner/work/partnership/partnership/spec/cypress/
      #     retention-days: 5

      # - name: 'Upload Cypress videos and screenshots when done'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: cypress_videos
      #     path: /home/runner/work/partnership/partnership/spec/cypress/
      #     retention-days: 5